// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: example.sql

package sqlcdb

import (
	"context"
)

const countExamples = `-- name: CountExamples :one
SELECT count(*) FROM examples
`

func (q *Queries) CountExamples(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countExamples)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExample = `-- name: CreateExample :one
INSERT INTO examples (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateExample(ctx context.Context, name string) (Example, error) {
	row := q.db.QueryRow(ctx, createExample, name)
	var i Example
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExamples = `-- name: ListExamples :many
SELECT id, name, created_at, updated_at
FROM examples
ORDER BY id DESC
LIMIT $2::bigint OFFSET $1::bigint
`

type ListExamplesParams struct {
	Off int64
	Lim int64
}

func (q *Queries) ListExamples(ctx context.Context, arg ListExamplesParams) ([]Example, error) {
	rows, err := q.db.Query(ctx, listExamples, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Example
	for rows.Next() {
		var i Example
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
