// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for CreateTokenResTokenType.
const (
	Bearer CreateTokenResTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the CreateTokenResTokenType enum.
func (e CreateTokenResTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseChecks.
const (
	HealthResponseChecksNotConfigured HealthResponseChecks = "not_configured"
	HealthResponseChecksOk            HealthResponseChecks = "ok"
	HealthResponseChecksUnavailable   HealthResponseChecks = "unavailable"
)

// Valid indicates whether the value is a known member of the HealthResponseChecks enum.
func (e HealthResponseChecks) Valid() bool {
	switch e {
	case HealthResponseChecksNotConfigured:
		return true
	case HealthResponseChecksOk:
		return true
	case HealthResponseChecksUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusDegraded  HealthResponseStatus = "degraded"
	HealthResponseStatusOk        HealthResponseStatus = "ok"
	HealthResponseStatusUnhealthy HealthResponseStatus = "unhealthy"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case HealthResponseStatusDegraded:
		return true
	case HealthResponseStatusOk:
		return true
	case HealthResponseStatusUnhealthy:
		return true
	default:
		return false
	}
}

// CreateExampleReq 创建示例的请求体。
type CreateExampleReq struct {
	// Name 名称；不可为空，最长 255。
	Name string `json:"name"`
}

// CreateTokenEnvelope defines model for CreateTokenEnvelope.
type CreateTokenEnvelope struct {
	// Code 业务错误码。0 表示成功；非 0 详见 `pkg/errcode` 与 `docs/errcodes.md`。
	Code int `json:"code"`

	// Data 签发成功返回的 token 数据。
	Data *CreateTokenRes `json:"data,omitempty"`

	// Message 人读的默认英文文案；按 reason 查 `pkg/response.MessageFor` 表。
	Message string `json:"message"`

	// Metadata 附加元信息。
	Metadata *struct {
		// TraceId 本次请求的 trace_id；与日志、X-Request-ID 头同源，用于反查链路。
		TraceId *string `json:"trace_id,omitempty"`
	} `json:"metadata,omitempty"`

	// Reason 机器可读的错误常量（如 `INVALID_PARAMS`、`DATABASE_ERROR`）。前端用它做分支判断。
	Reason *string `json:"reason,omitempty"`
}

// CreateTokenReq 签发示例 token 的请求体。
type CreateTokenReq struct {
	// Subject 要签进 token 的 subject（通常是用户 ID 或用户名）。不可为空。
	Subject string `json:"subject"`
}

// CreateTokenRes 签发成功返回的 token 数据。
type CreateTokenRes struct {
	// AccessToken HS256 签名的 JWT。客户端把它放进 `Authorization: Bearer <token>` 头。
	AccessToken string `json:"access_token"`

	// TokenType 固定为 "Bearer"。
	TokenType CreateTokenResTokenType `json:"token_type"`
}

// CreateTokenResTokenType 固定为 "Bearer"。
type CreateTokenResTokenType string

// EnqueueExampleTaskEnvelope defines model for EnqueueExampleTaskEnvelope.
type EnqueueExampleTaskEnvelope struct {
	// Code 业务错误码。0 表示成功；非 0 详见 `pkg/errcode` 与 `docs/errcodes.md`。
	Code int `json:"code"`

	// Data 投递结果。
	Data *EnqueueExampleTaskRes `json:"data,omitempty"`

	// Message 人读的默认英文文案；按 reason 查 `pkg/response.MessageFor` 表。
	Message string `json:"message"`

	// Metadata 附加元信息。
	Metadata *struct {
		// TraceId 本次请求的 trace_id；与日志、X-Request-ID 头同源，用于反查链路。
		TraceId *string `json:"trace_id,omitempty"`
	} `json:"metadata,omitempty"`

	// Reason 机器可读的错误常量（如 `INVALID_PARAMS`、`DATABASE_ERROR`）。前端用它做分支判断。
	Reason *string `json:"reason,omitempty"`
}

// EnqueueExampleTaskReq 投递异步任务的请求体。
type EnqueueExampleTaskReq struct {
	// Name 任务名（业务自定义）；长度 1-255。
	Name string `json:"name"`
}

// EnqueueExampleTaskRes 投递结果。
type EnqueueExampleTaskRes struct {
	// Queued true = 已成功入队（不代表已执行）。
	Queued bool `json:"queued"`
}

// Envelope 统一响应信封。成功 `code: 0`；失败带非 0 `code`、稳定 `reason` 串
// 和可选的 `metadata.trace_id`，方便前端报问题时给后端定位日志。
type Envelope struct {
	// Code 业务错误码。0 表示成功；非 0 详见 `pkg/errcode` 与 `docs/errcodes.md`。
	Code int `json:"code"`

	// Message 人读的默认英文文案；按 reason 查 `pkg/response.MessageFor` 表。
	Message string `json:"message"`

	// Metadata 附加元信息。
	Metadata *struct {
		// TraceId 本次请求的 trace_id；与日志、X-Request-ID 头同源，用于反查链路。
		TraceId *string `json:"trace_id,omitempty"`
	} `json:"metadata,omitempty"`

	// Reason 机器可读的错误常量（如 `INVALID_PARAMS`、`DATABASE_ERROR`）。前端用它做分支判断。
	Reason *string `json:"reason,omitempty"`
}

// ErrorEnvelope 统一响应信封。成功 `code: 0`；失败带非 0 `code`、稳定 `reason` 串
// 和可选的 `metadata.trace_id`，方便前端报问题时给后端定位日志。
type ErrorEnvelope = Envelope

// Example 示例资源实体。
type Example struct {
	// CreatedAt 创建时间（RFC3339，UTC）。
	CreatedAt time.Time `json:"created_at"`

	// Id 主键，单调递增。
	Id int64 `json:"id"`

	// Name 名称；长度 1-255，与 DB `varchar(255)` 对齐。
	Name string `json:"name"`

	// UpdatedAt 最近一次更新时间（RFC3339，UTC）。
	UpdatedAt time.Time `json:"updated_at"`
}

// ExampleEnvelope defines model for ExampleEnvelope.
type ExampleEnvelope struct {
	// Code 业务错误码。0 表示成功；非 0 详见 `pkg/errcode` 与 `docs/errcodes.md`。
	Code int `json:"code"`

	// Data 示例资源实体。
	Data *Example `json:"data,omitempty"`

	// Message 人读的默认英文文案；按 reason 查 `pkg/response.MessageFor` 表。
	Message string `json:"message"`

	// Metadata 附加元信息。
	Metadata *struct {
		// TraceId 本次请求的 trace_id；与日志、X-Request-ID 头同源，用于反查链路。
		TraceId *string `json:"trace_id,omitempty"`
	} `json:"metadata,omitempty"`

	// Reason 机器可读的错误常量（如 `INVALID_PARAMS`、`DATABASE_ERROR`）。前端用它做分支判断。
	Reason *string `json:"reason,omitempty"`
}

// HealthResponse readiness 探针响应。
type HealthResponse struct {
	// Build 构建期元信息（ldflags 注入）。让监控直接从 /health 抓版本号，不必
	// 再单独开一个版本端点。
	Build struct {
		// BuildTime 构建时间戳（RFC3339，UTC）。
		BuildTime string `json:"build_time"`

		// Commit 短 commit SHA。
		Commit string `json:"commit"`

		// Version 语义化版本号或 tag 名。
		Version string `json:"version"`
	} `json:"build"`

	// Checks 每个依赖的健康状态，key 是依赖名：postgres（关键依赖，异常直接
	// unhealthy）、redis（缓存，非关键）、queue（Asynq 队列，探测底层
	// Redis 连通性，非关键）。非关键依赖异常只触发 degraded，不摘流。
	Checks map[string]HealthResponseChecks `json:"checks"`

	// Status ok: 全部依赖可达；degraded: 非关键依赖（Redis）异常，HTTP 仍 200，
	// LB 不摘流；unhealthy: 关键依赖（Postgres）异常，HTTP 503，LB 摘流。
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseChecks defines model for HealthResponse.Checks.
type HealthResponseChecks string

// HealthResponseStatus ok: 全部依赖可达；degraded: 非关键依赖（Redis）异常，HTTP 仍 200，
// LB 不摘流；unhealthy: 关键依赖（Postgres）异常，HTTP 503，LB 摘流。
type HealthResponseStatus string

// ListExamplesEnvelope defines model for ListExamplesEnvelope.
type ListExamplesEnvelope struct {
	// Code 业务错误码。0 表示成功；非 0 详见 `pkg/errcode` 与 `docs/errcodes.md`。
	Code int `json:"code"`

	// Data 分页查询的响应数据。
	Data *ListExamplesRes `json:"data,omitempty"`

	// Message 人读的默认英文文案；按 reason 查 `pkg/response.MessageFor` 表。
	Message string `json:"message"`

	// Metadata 附加元信息。
	Metadata *struct {
		// TraceId 本次请求的 trace_id；与日志、X-Request-ID 头同源，用于反查链路。
		TraceId *string `json:"trace_id,omitempty"`
	} `json:"metadata,omitempty"`

	// Reason 机器可读的错误常量（如 `INVALID_PARAMS`、`DATABASE_ERROR`）。前端用它做分支判断。
	Reason *string `json:"reason,omitempty"`
}

// ListExamplesRes 分页查询的响应数据。
type ListExamplesRes struct {
	// Examples 当前页结果。
	Examples []Example `json:"examples"`

	// Total 满足查询条件的总条数（用于前端算总页数）。
	Total int64 `json:"total"`
}

// LivenessResponse liveness 探针响应。
type LivenessResponse struct {
	// Status 永远是 "ok"——探针硬编码成功。
	Status string `json:"status"`

	// Version 通过 ldflags 注入的构建版本号，用于快速确认"现在跑的是哪一版"。
	Version string `json:"version"`
}

// MeEnvelope defines model for MeEnvelope.
type MeEnvelope struct {
	// Code 业务错误码。0 表示成功；非 0 详见 `pkg/errcode` 与 `docs/errcodes.md`。
	Code int `json:"code"`

	// Data 当前已鉴权主体信息。
	Data *MeRes `json:"data,omitempty"`

	// Message 人读的默认英文文案；按 reason 查 `pkg/response.MessageFor` 表。
	Message string `json:"message"`

	// Metadata 附加元信息。
	Metadata *struct {
		// TraceId 本次请求的 trace_id；与日志、X-Request-ID 头同源，用于反查链路。
		TraceId *string `json:"trace_id,omitempty"`
	} `json:"metadata,omitempty"`

	// Reason 机器可读的错误常量（如 `INVALID_PARAMS`、`DATABASE_ERROR`）。前端用它做分支判断。
	Reason *string `json:"reason,omitempty"`
}

// MeRes 当前已鉴权主体信息。
type MeRes struct {
	// Subject 从 Bearer token 解析出的 subject。
	Subject string `json:"subject"`
}

// BadRequest 错误响应信封。结构与 Envelope 一致，但 `data` 永远为空。完整的
// code / reason 目录见 `docs/errcodes.md`。
type BadRequest = ErrorEnvelope

// Forbidden 错误响应信封。结构与 Envelope 一致，但 `data` 永远为空。完整的
// code / reason 目录见 `docs/errcodes.md`。
type Forbidden = ErrorEnvelope

// InternalError 错误响应信封。结构与 Envelope 一致，但 `data` 永远为空。完整的
// code / reason 目录见 `docs/errcodes.md`。
type InternalError = ErrorEnvelope

// NotImplemented 错误响应信封。结构与 Envelope 一致，但 `data` 永远为空。完整的
// code / reason 目录见 `docs/errcodes.md`。
type NotImplemented = ErrorEnvelope

// RequestTimeout 错误响应信封。结构与 Envelope 一致，但 `data` 永远为空。完整的
// code / reason 目录见 `docs/errcodes.md`。
type RequestTimeout = ErrorEnvelope

// ServiceUnavailable 错误响应信封。结构与 Envelope 一致，但 `data` 永远为空。完整的
// code / reason 目录见 `docs/errcodes.md`。
type ServiceUnavailable = ErrorEnvelope

// TooManyRequests 错误响应信封。结构与 Envelope 一致，但 `data` 永远为空。完整的
// code / reason 目录见 `docs/errcodes.md`。
type TooManyRequests = ErrorEnvelope

// Unauthorized 错误响应信封。结构与 Envelope 一致，但 `data` 永远为空。完整的
// code / reason 目录见 `docs/errcodes.md`。
type Unauthorized = ErrorEnvelope

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListExamplesParams defines parameters for ListExamples.
type ListExamplesParams struct {
	// Limit 分页大小。默认 20；省略或传 0 时回退到默认。
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset 分页偏移（跳过的行数）。从 0 开始。
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateAuthTokenJSONRequestBody defines body for CreateAuthToken for application/json ContentType.
type CreateAuthTokenJSONRequestBody = CreateTokenReq

// CreateExampleJSONRequestBody defines body for CreateExample for application/json ContentType.
type CreateExampleJSONRequestBody = CreateExampleReq

// EnqueueExampleTaskJSONRequestBody defines body for EnqueueExampleTask for application/json ContentType.
type EnqueueExampleTaskJSONRequestBody = EnqueueExampleTaskReq

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 返回当前 Bearer token 的 subject
	// (GET /api/v1/auth/me)
	GetAuthMe(c *gin.Context)
	// 签发示例 JWT（仅开发环境）
	// (POST /api/v1/auth/token)
	CreateAuthToken(c *gin.Context)
	// 列出示例（按创建时间倒序）
	// (GET /api/v1/examples)
	ListExamples(c *gin.Context, params ListExamplesParams)
	// 创建一个示例
	// (POST /api/v1/examples)
	CreateExample(c *gin.Context)
	// 投递一个示例异步任务到 Asynq
	// (POST /api/v1/examples/tasks)
	EnqueueExampleTask(c *gin.Context)
	// 就绪探针（依赖健康检查）
	// (GET /health)
	GetHealth(c *gin.Context)
	// 存活探针
	// (GET /livez)
	GetLivez(c *gin.Context)
	// 返回原始 OpenAPI 3.1 spec
	// (GET /openapi.json)
	GetOpenAPISpec(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAuthMe operation middleware
func (siw *ServerInterfaceWrapper) GetAuthMe(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAuthMe(c)
}

// CreateAuthToken operation middleware
func (siw *ServerInterfaceWrapper) CreateAuthToken(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateAuthToken(c)
}

// ListExamples operation middleware
func (siw *ServerInterfaceWrapper) ListExamples(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListExamplesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListExamples(c, params)
}

// CreateExample operation middleware
func (siw *ServerInterfaceWrapper) CreateExample(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateExample(c)
}

// EnqueueExampleTask operation middleware
func (siw *ServerInterfaceWrapper) EnqueueExampleTask(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.EnqueueExampleTask(c)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GetLivez operation middleware
func (siw *ServerInterfaceWrapper) GetLivez(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLivez(c)
}

// GetOpenAPISpec operation middleware
func (siw *ServerInterfaceWrapper) GetOpenAPISpec(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOpenAPISpec(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/v1/auth/me", wrapper.GetAuthMe)
	router.POST(options.BaseURL+"/api/v1/auth/token", wrapper.CreateAuthToken)
	router.GET(options.BaseURL+"/api/v1/examples", wrapper.ListExamples)
	router.POST(options.BaseURL+"/api/v1/examples", wrapper.CreateExample)
	router.POST(options.BaseURL+"/api/v1/examples/tasks", wrapper.EnqueueExampleTask)
	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.GET(options.BaseURL+"/livez", wrapper.GetLivez)
	router.GET(options.BaseURL+"/openapi.json", wrapper.GetOpenAPISpec)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1HtrUxrZuv9XWcX//2LiNoK3fU48NbXLjMwZs41mK5k5+2xS0oGOYUe6SdOk4p6yClQUFMQkeAkaDRlv",
	"k0QgMSqBNnyXSa/VzSu+wqm1VoMNNDEzZ+LUqZqqiX1Z/Vx+z/3hR5OT93h5juVEn6nnR5PA+rw852PJ",
	"H1cZ1zB738/6RPyXk+dEliP/ZLzecbeTEd08Z/6nj+fwNZ/zLuth8L/+v8DeMfWY/p/57GgzveszWwWB",
	"F6zcA3ac97KmycnJVpOL9TkFtxcfZuoxwfQLFD5RXmVKiadqJlOWwu0PHz4EKH1UliIfA1Mwl1P3gmUp",
	"6egf/L53oL9v9EbvcO/1EQf4qt1iab8EYHwKLWfR81TpZRRuv1Hf7XwMTNm527xrAsjFFMwGYW5XeftB",
	"SaWV5AxwCCzj4zkHMAOHk3exjrIUrdKAYml0sA3DsyiRgeFttHJAzjJNtpq+5YXbbpeL5S5QNCdvS5F3",
	"6Nm0fDqLVp+jZ9Olp0sfA1MaC1/fsA5f7x8Z6R8aHO2zDvZb+xxlKYx5Au0WSycVHyW+nxNZgWPGyScv",
	"jgG0EYPzKeVVBoY2YH65quErNRpWd2eV9RXg6B+0WYcHewdGrcPDQ8MO8NUVrN+PgaCdc/T12nqv9o5Y",
	"9fc68D3H325ab9Zc7roElIMz1gd5sd/jHWc9LCeyrovjXXmVUabew5O36kwSRRbQ5rGS2ELhJfl0Vs4l",
	"4XyqFCioHx6hjZcwvaksZnV6HRyyjfZfvzFgvW4dtFn7Rv9utVU1e8Vi6dZrVrNXm9vD8v4LNFs1c4Le",
	"TMHtGWVpVj0OqcW5UiimnBITq6VJx9iw9W83rSO2UVv/devQTZserjVMjbDCA7eTvckxDxj3OHN7nL04",
	"xuTcAsrl5A/P1KMVOReD8YyS2EfhFapP9cUryieUAjB0CEOHpdUDHYYpGm8O9n7f2z/Qe3XASjHZecnO",
	"yblF4BixDn/f/411tK9/BN/to17sz5d+CSR+CSRgJKYGQmpqX9nOUwpQcgqtHqPolJyf/RgIwnimNBdT",
	"M8tlaR0uLaqBkJ2jj1OqUCBYISlIH0Srz5XEPvajFR+nJPYBcY5VTwijeRierUrfxvPXGW5C06LvAjG1",
	"twvjj0pPl9BRUIca29DQ6PXewb+PavAZ0eOmS4+bmxzjF+/ygvtfF2np1EfT0IOBIuVh9hGcO1AzwbIU",
	"Fvl7LAfwxe03wAzU4hza2AJmoBx8gEsx7NaXwxUeKhzfHOy9aftuaLj/v2t9escZs5OtGvlEP98ILCOy",
	"1ocM9nTD7H18rS6WhNdhIU9wtaAkZ6j5yqdPPgamTK0mr8B7WUF00zSAYzyswQlLMWUvW5bWqVXIubzy",
	"c74sRdFGoLRcBB3d3fQsD/NwgOXGxLumno7u7laTx81V/m5vNYkTXtbUY/KJgpsbI2wI7H2/W8AK+wf9",
	"8q3qU/ztf7JOEWuWMmjDsqyqAmt1fHzojqnnH+dosKq81h/rWHUx4rkA0H17mPURmuvou1VLoaECsL7j",
	"j6gCgAaKc/Tg89PzG85Sd4PKwQe1uH52ENAeLkvhUiAJczm0Rh3XCejvAxiW5A+4FKMY0itR09uv0FOF",
	"snNUNcz6GomngkDhJTi/pRYTcH0Tk08ZwYlcLG0kC8bpZH2+UfJY45nfjXR0/1kzKXzatR9sepeH5udh",
	"eholiMgcvZqPIM6gB1xlGYEVgN1vsXQ6yfnkn6wDwO13lJQ6YbSayGOj9HKDnaznYTop5/LAbqJn2030",
	"GJbze7D06FXTrYaD66Rcw3PNR43kbuXu+1l/xQnYGN+9C7eURhI+YTBGDxvYDZpfLgUeQ2kKHezIhQLO",
	"J3+T+6LvEvyHaQKmzr3EinofKUuRsrReWi7C/C5ov/xlPZmxjJqwrRSeoM0NIybJIa7G90TBz4KvATx5",
	"Sy0MhnZKa1uE55hc+ElN7eNbkT01FaWO4Azet3l+nGW4Bla0Txkzc4awOisvbMm5AHwSg/kErcI+BqYo",
	"SbTu6gEWB85iSNiEud3Ss01gobccHwNBZf8QppNnOYqce2vn4OMozoACEVLIeViRwahsEwXGyY66XbiU",
	"Qyvv5Q9FGIkRs98praZLL9bQ6rFSeAqXFnEpkk7KpzG0ugOLqzSW1osWk2CAH5q0kxJGeY65sQCaelGu",
	"MIIIC2pmV90LAof33piZFQTCECDJn4t3+iqXfG0el6NG/G5OZMdYAYvVw/p8zJgREfm8mikoyZlSYU1N",
	"b6sLb9DKHP4vFS5L6ygaAVReAG3tUAoq9X3bdXrmt7zgwHQ3cWwVmTZ+uvR0Bs4/h6FpuZhCwYwRJit6",
	"MEDzxmv0OkWtlnh77UmSTSxWlBH8r8ta0nm5vw97X7gURfmlshRVEvtyfhHGY2hrp/Tkg3qSMaR/0gCi",
	"VCBGJOXh030Yz2gCJYqFuVxpLl6WwnB3CtQ3HHC1WVeHai0KgjYlsQ/T0zCYrGsfmM5zFQRvZ0o3tLOa",
	"HPQ3uPNbDUkr5bfWPom7mcFYrbwJ5FxAnXtXlqLy6SxwYGg4AMrm1OJGNXeA6ShafqckZ+wcSVTNFRAq",
	"62l4ukyMwQj6NGfXHKGBByGpkno0g/JLML3ZxNk7SbbhGmXEZjkvWj0urb4rS+Hhb7/p7Oy8UpaiN23f",
	"VJ3fHV7w4JdxgGMvi24Pa2QXRqCWc4VSIo3bR7FlNTuNo9SLzbpD3Zz45y6aXLk9fo8+cOjs/ZyEWx+Z",
	"sCZyi6DvKnA8YATnXUb4qqO7+5IDwMz70ulSE7P2e11NpYQ2AmrxkZwLoNcptP4OrWR/B4nVQdztMmlc",
	"tuo1VkOYIe4pOC4+kdFA2SR1+Y5lxsW7w5prbRSpwDIuN8f6fAAtvig9DlMzM4Lvbb973Mhfbs5g5G5s",
	"Vf1tWQqPu+6MM2M+gA73YWhH652lf1bWH6HFPWX9HVrckQuLwHyXUAfQ/BMlEkYbr2H8hKAmBoshOwdn",
	"YzC2rCy8hlJAzgXk3Ev6FO1vGEdEQuUo0XQzUglkUPiwKWoaMOnkPR63AR6VrQNA74GR73qbvPyAFXxu",
	"I7euZg7k9xEYXanyjsIrQGTGAFyKfY43rpxcJbBVz74RSJ13Wec9WqS4XG5MBzN+o0Z+lcSfv4chr+tq",
	"tZo4Xhx18twd95hfqEmyznitk3cmLude0u6QkpyBwR2YP1Hmj1EgWJai99gJgNYy9DZJdpNe3ieOCawP",
	"R7XQYSmRpjex35Jwd50ix875OQqcCaKyoMC63PgdRXoCD9bKUrT0bJO+T++TrLAshXt9E9x9UFrbguFV",
	"nH8tvkBHCzC/DN9M2blhfAhQi5ulQBIF9hpOmar+qVFMKILxl7QVBFzsmMC4WBfFL3q0RjtDBKINevCJ",
	"jOg3SKX5ez0AhvZL0/vaR+IZ9cOHsrReOb0H1JGBQUzZj1CKylL0O5vtBpALMdBhsZSlqJ0buAqqNJWl",
	"9ar4ekDdUTeqCqg7rRs36aMDV0EtYzVoqdBIgKN94fzKURNFFZsahg3hO+D2iZq/8124o9V//BO1Yv1j",
	"BqF+tpQ6Qls7auYFtgricJt3E1jtLIODTp/ASKyUOtKXXm6R9fg+O2ZUOWAEgZkgf/MiM27gOgsp9fiQ",
	"Eo2epeTCsZKcQYECepZCy1lsezTtpellehUFCpjJ5Sy1nU/mGZbGPKMOI1UZVOgzBscDFgey5rFuXHvi",
	"3FDXzDxpNonWMsBu4u/ZTbQVTk9TUq8VaUV5HqQ1Fj2WrWSM1EI+PzaUAkm1OAdq4ygWOQlh+mCpCb74",
	"qhTYUlJpNb1tNymLWbixr548wm+sZeCTl3IuoETCle7OZ1pkhTojaV+/+EznOvsJs6M3m9jI2XQyV5BP",
	"nzQvC5u2MXG2onXfaPtP3fsJbS7BubyuoflZwm3ajsRhgXX6Bbc4MYI51vIZ8lHcBzz769uKKV37wWbS",
	"muukK0LunpFwVxS9dArg5u7wlSkDQ/mjibxpjL/su8eOsyLPNQZw3U2gDUiTM3A2VJreB703+gHceaTk",
	"d0kwsHNKfhemk2UpaecuA9qCoBZG+yvyaRGPcxw/4rqqFWglZKtWgP2lFWAI/KUVVMr6v0w6QLXas3OA",
	"9lvA18DiMG5mkNvYNmvbGbRvpiRnaJumrjeCD67M8RvG+1E6/K1MhiuX6VzjMiCBkRoLwP0M/XfbSBnc",
	"hh8ZIU98dckB0NpzmJ2hEy38EJEVAFqr6ZfZxzRgrxNq8J9dFou5y9Ju7rJ0mrssXeYuy7+buzqumEk0",
	"Xr9SeazbYjF3W9rxZU1WVVZwyVzYAQ78zTZNIMEkXTHQdESK/7K0rmcHxl/Kp6RsJhn7x0Bw4CqZbgNQ",
	"CsTR2qJc+ElZmqU6xbJ9u6q8fQzzu1hj8RNNQHArr6QCavoDWjmlOTtwmLET/pfWZdLyf/xXTD3KUoKo",
	"0rFnI9ke7btjyWD+gFJ4iqn4q/82K3CsyFacOSWlmnC5xfE6dGPA6nxaj8nS1t5mwZjnvSzHeN2mHlMn",
	"udRq8jLiXWJ9ZsbrNj9oN+NZnZmWFGOsUWFKVjp+Xb++LEU13j7pUezc54zl0OqxWkyALkt7WQo76oZy",
	"kYpYsKsjpPW7TD2m/2RFTO91nNvX7NZ0WCy/20hSFycMJ9h6ja/TqEeFiVaPaROnTZOFA6ClPMztUpdO",
	"PTn2uJOtpi5LezM6qoyZayauk62mbovl/Jdqt1H0PppEO713/sct3Lry+T0eRpjA5R1RLqW2NnboFIyx",
	"yoz5yAgFn3ILf6IGddUxEi6ODIrIk4ySeNPSAvcWlEK4pQVnCrNRPJK+9oNtdMT6zbDV5sA9djp1l3MJ",
	"4MDgGO2zfj9qG/qrdXDUOkjm+1/jfrzDzuEONJl7ATqqIgSQIf4uDD9Viwm90qhX/hovBpA1JW0q3LA7",
	"QMqQ+t0lMsu3a+snuOg/WIMb+3aTnFusXFVfvIKhQ5K3tLQoiS05v6csZuCLaVgMlVKF6lJDS4sBwOl4",
	"D2vHps2lBNqzvcq7Jn43hNdNU432a4g46fIXzRHOMgIs9MkvaH9G0+jzDZGGpKoJOgA8WEXpI2qAFBFV",
	"0/sMK9It6/1Gw8NvdZ7/lsE2zuSk3ihrRtvXfrDhaVMhhDdk4o8osMpS5JNGqa/HDGNBTX2nbwyHV+kw",
	"Q+8YaJGEYmnwJ6AvpxykznGQcd/Zzp+do5ajplP6GovgH0p52gBHgT1A3m5pKUtJmq2pR1ngGGa9LCNi",
	"oQyzjAv8CeD/DXHjEw47J+cX4HwK9y6Kz9RMEIy7fSKAj6P0JICe7eAR5FIUD8qKr5QQTgnwmE5KUhJg",
	"BhuwnJs3DjX6opjEV4HxsCIr+IgXNZIf3N6D2Thuu5DxEejAiZGyEVSW8eKKLD0HFoBWj+H6ZikQgOEs",
	"fUyrgfEx9/2sMFFp5eLajzbIzqzGwzzU+twWy6e73pOtTWgMxpW9QlkKqyeHanEOD3tT0WrNi0sGC8DQ",
	"2ltoThd/546PrSPsU4XxrS/oKwzbK+c7CwMXgTZe1/QlLs5R1Fg7DK/ifIoYYVkKo2hEP2eBgccwH6+1",
	"90rBjktK44ALN/aBQ3vMR0oRFH8MQzt4KvEspaaz8HQZh1+s34pQ8Du33ZzLzY2B0toxvhJM0jTHzuE1",
	"mMapSeULbfgcAMOrxkMU6iDU41BpuVjNl+1c/TyQNiVlKQnDWTyQgW+mjA21ZjvriwZM3QaY0T4x0dMf",
	"EzLrJzm/zQJWsrhRk5yhzv8PNQIsSm1+QkzBEO8GIc4sMj46LTA2BTQ/r62qpDbxupK+v063YOj2xsfA",
	"FO2um7VH0MZLbQmUlC12zmAZVbdF3ElRXmlEawuo1RI3Xt2Fx5UsWsvYObupcSfVblKLa3jVbGMLz2hp",
	"8Xu2hN9gCo3bL1/IHoy3i4xQR4X9xxhF85WtX51OtpGjXLjszwNM+P/NXJLuPekNS7/6hT0tQXtTa6PN",
	"j6Z5JO6sEKjSRhOdmynP8aJuh8UCzHQmE1EKTwGZ7yzqmyI4vhwFS3NxOHuoHKyQhYmndq5+2qsk9jVr",
	"IoYgS0k1/TOojnnk09mWFjkXa2kpzcXgUgZ4eRfeoiBtPe2OepS1c1qLr9K5qXa4NJdYre2aNiLomPpL",
	"NiLqBuFNfwJCp5R4PBgJoI0ILIbU3aB+GqeBVcPQBdFGUYbCK3A7Kede6qmqbv4Twmpdf/aNUnhJVY0r",
	"HcoFYRD9FEBbO7XJjwZIik7Sp2sKTrW4ruwv4CFDcUlNRWH2DZ2N4CZUh8VC8aYHZN3spRF4FGF2zsvj",
	"ESpcf44OtgnE1OnTlhaN1UJBPl2G2yul6X3lsKAU8LZg31VgBjS+KAeRT3W7BghLXzSBrhtBGf1ygEru",
	"YA29KxhojFynMmqmGa1f2VahzVBBuOt7bWRoEMDTF1CKazXnbAgeRXH7acjLcriD39nWDtS9GTU6je06",
	"noEZCYZ2AJ4DexgOmMFVwc/xwGzn+jkf7+HcDBYy/iHN3k/VQ/BQ4GQHhk5wjTi/T388VI3PwAw8vPNe",
	"U61op4x4Wef/VjfGSw04wjROWxoUoxeJz8s6G5WjCXFxC+4tgPrHddrCIwysK/wyKzwwLnMHeCczDlws",
	"CaL4F1/gK7fHywsicLF3GP+4+B/AjFfRAP+AFQS3i/UBRgSCn8PLHZfwjF0Y12Y8PWZze8e/tVnaLG3t",
	"PZ0Wi4Us0WnU1H9Xb/7VRZpqW/7TVotrKL2ZY0Ml9mvnqhYMiAHjLeWz9j4+tT70VP1R1X/hQ+v2DPBP",
	"kWL0XJ1ha6WzZhSN1fm1H2yAzvtoWCYMnjVTHUAuhLSxqa7x0/irBzLWxi1H2makXNk5R2Uc4AD0FO0H",
	"nQadXvj+WOvx6xv6ZywwfkMG9G0jHImkhLKdp7uLdDGV7HEk9T8nJYMgH01ZtOkbuSSwXt7nFnlhAqhL",
	"pzD/xM7hy8Y7zytZtJ+Cz1aV0J766JU6v6skCsqTFzB2COOZOtLZ6g5BPfVkMlhZBqMQK0vhir1gW8HD",
	"i7MRdkT/+weczS9E6FN6d4IHTs+DdTQQQ5u8Nfk/AwA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
