// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for CreateTokenResTokenType.
const (
	Bearer CreateTokenResTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the CreateTokenResTokenType enum.
func (e CreateTokenResTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseChecks.
const (
	HealthResponseChecksNotConfigured HealthResponseChecks = "not_configured"
	HealthResponseChecksOk            HealthResponseChecks = "ok"
	HealthResponseChecksUnavailable   HealthResponseChecks = "unavailable"
)

// Valid indicates whether the value is a known member of the HealthResponseChecks enum.
func (e HealthResponseChecks) Valid() bool {
	switch e {
	case HealthResponseChecksNotConfigured:
		return true
	case HealthResponseChecksOk:
		return true
	case HealthResponseChecksUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusDegraded  HealthResponseStatus = "degraded"
	HealthResponseStatusOk        HealthResponseStatus = "ok"
	HealthResponseStatusUnhealthy HealthResponseStatus = "unhealthy"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case HealthResponseStatusDegraded:
		return true
	case HealthResponseStatusOk:
		return true
	case HealthResponseStatusUnhealthy:
		return true
	default:
		return false
	}
}

// CreateExampleReq 创建示例的请求体。
type CreateExampleReq struct {
	// Name 名称；不可为空，最长 255。
	Name string `json:"name"`
}

// CreateTokenEnvelope defines model for CreateTokenEnvelope.
type CreateTokenEnvelope struct {
	// Code 业务错误码。0 表示成功；非 0 详见 `pkg/errcode` 与 `docs/errcodes.md`。
	Code int `json:"code"`

	// Data 签发成功返回的 token 数据。
	Data *CreateTokenRes `json:"data,omitempty"`

	// Message 人读的默认英文文案；按 reason 查 `pkg/response.MessageFor` 表。
	Message string `json:"message"`

	// Metadata 附加元信息。
	Metadata *struct {
		// TraceId 本次请求的 trace_id；与日志、X-Request-ID 头同源，用于反查链路。
		TraceId *string `json:"trace_id,omitempty"`
	} `json:"metadata,omitempty"`

	// Reason 机器可读的错误常量（如 `INVALID_PARAMS`、`DATABASE_ERROR`）。前端用它做分支判断。
	Reason *string `json:"reason,omitempty"`
}

// CreateTokenReq 签发示例 token 的请求体。
type CreateTokenReq struct {
	// Subject 要签进 token 的 subject（通常是用户 ID 或用户名）。不可为空。
	Subject string `json:"subject"`
}

// CreateTokenRes 签发成功返回的 token 数据。
type CreateTokenRes struct {
	// AccessToken HS256 签名的 JWT。客户端把它放进 `Authorization: Bearer <token>` 头。
	AccessToken string `json:"access_token"`

	// TokenType 固定为 "Bearer"。
	TokenType CreateTokenResTokenType `json:"token_type"`
}

// CreateTokenResTokenType 固定为 "Bearer"。
type CreateTokenResTokenType string

// EnqueueExampleTaskEnvelope defines model for EnqueueExampleTaskEnvelope.
type EnqueueExampleTaskEnvelope struct {
	// Code 业务错误码。0 表示成功；非 0 详见 `pkg/errcode` 与 `docs/errcodes.md`。
	Code int `json:"code"`

	// Data 投递结果。
	Data *EnqueueExampleTaskRes `json:"data,omitempty"`

	// Message 人读的默认英文文案；按 reason 查 `pkg/response.MessageFor` 表。
	Message string `json:"message"`

	// Metadata 附加元信息。
	Metadata *struct {
		// TraceId 本次请求的 trace_id；与日志、X-Request-ID 头同源，用于反查链路。
		TraceId *string `json:"trace_id,omitempty"`
	} `json:"metadata,omitempty"`

	// Reason 机器可读的错误常量（如 `INVALID_PARAMS`、`DATABASE_ERROR`）。前端用它做分支判断。
	Reason *string `json:"reason,omitempty"`
}

// EnqueueExampleTaskReq 投递异步任务的请求体。
type EnqueueExampleTaskReq struct {
	// Name 任务名（业务自定义）；长度 1-255。
	Name string `json:"name"`
}

// EnqueueExampleTaskRes 投递结果。
type EnqueueExampleTaskRes struct {
	// Queued true = 已成功入队（不代表已执行）。
	Queued bool `json:"queued"`
}

// Envelope 统一响应信封。成功 `code: 0`；失败带非 0 `code`、稳定 `reason` 串
// 和可选的 `metadata.trace_id`，方便前端报问题时给后端定位日志。
type Envelope struct {
	// Code 业务错误码。0 表示成功；非 0 详见 `pkg/errcode` 与 `docs/errcodes.md`。
	Code int `json:"code"`

	// Message 人读的默认英文文案；按 reason 查 `pkg/response.MessageFor` 表。
	Message string `json:"message"`

	// Metadata 附加元信息。
	Metadata *struct {
		// TraceId 本次请求的 trace_id；与日志、X-Request-ID 头同源，用于反查链路。
		TraceId *string `json:"trace_id,omitempty"`
	} `json:"metadata,omitempty"`

	// Reason 机器可读的错误常量（如 `INVALID_PARAMS`、`DATABASE_ERROR`）。前端用它做分支判断。
	Reason *string `json:"reason,omitempty"`
}

// ErrorEnvelope 统一响应信封。成功 `code: 0`；失败带非 0 `code`、稳定 `reason` 串
// 和可选的 `metadata.trace_id`，方便前端报问题时给后端定位日志。
type ErrorEnvelope = Envelope

// Example 示例资源实体。
type Example struct {
	// CreatedAt 创建时间（RFC3339，UTC）。
	CreatedAt time.Time `json:"created_at"`

	// Id 主键，单调递增。
	Id int64 `json:"id"`

	// Name 名称；长度 1-255，与 DB `varchar(255)` 对齐。
	Name string `json:"name"`

	// UpdatedAt 最近一次更新时间（RFC3339，UTC）。
	UpdatedAt time.Time `json:"updated_at"`
}

// ExampleEnvelope defines model for ExampleEnvelope.
type ExampleEnvelope struct {
	// Code 业务错误码。0 表示成功；非 0 详见 `pkg/errcode` 与 `docs/errcodes.md`。
	Code int `json:"code"`

	// Data 示例资源实体。
	Data *Example `json:"data,omitempty"`

	// Message 人读的默认英文文案；按 reason 查 `pkg/response.MessageFor` 表。
	Message string `json:"message"`

	// Metadata 附加元信息。
	Metadata *struct {
		// TraceId 本次请求的 trace_id；与日志、X-Request-ID 头同源，用于反查链路。
		TraceId *string `json:"trace_id,omitempty"`
	} `json:"metadata,omitempty"`

	// Reason 机器可读的错误常量（如 `INVALID_PARAMS`、`DATABASE_ERROR`）。前端用它做分支判断。
	Reason *string `json:"reason,omitempty"`
}

// HealthResponse readiness 探针响应。
type HealthResponse struct {
	// Build 构建期元信息（ldflags 注入）。让监控直接从 /health 抓版本号，不必
	// 再单独开一个版本端点。
	Build struct {
		// BuildTime 构建时间戳（RFC3339，UTC）。
		BuildTime string `json:"build_time"`

		// Commit 短 commit SHA。
		Commit string `json:"commit"`

		// Version 语义化版本号或 tag 名。
		Version string `json:"version"`
	} `json:"build"`

	// Checks 每个依赖的健康状态，key 是依赖名（postgres / redis / asynq 等）。
	Checks map[string]HealthResponseChecks `json:"checks"`

	// Status ok: 全部依赖可达；degraded: 非关键依赖（Redis）异常，HTTP 仍 200，
	// LB 不摘流；unhealthy: 关键依赖（Postgres）异常，HTTP 503，LB 摘流。
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseChecks defines model for HealthResponse.Checks.
type HealthResponseChecks string

// HealthResponseStatus ok: 全部依赖可达；degraded: 非关键依赖（Redis）异常，HTTP 仍 200，
// LB 不摘流；unhealthy: 关键依赖（Postgres）异常，HTTP 503，LB 摘流。
type HealthResponseStatus string

// ListExamplesEnvelope defines model for ListExamplesEnvelope.
type ListExamplesEnvelope struct {
	// Code 业务错误码。0 表示成功；非 0 详见 `pkg/errcode` 与 `docs/errcodes.md`。
	Code int `json:"code"`

	// Data 分页查询的响应数据。
	Data *ListExamplesRes `json:"data,omitempty"`

	// Message 人读的默认英文文案；按 reason 查 `pkg/response.MessageFor` 表。
	Message string `json:"message"`

	// Metadata 附加元信息。
	Metadata *struct {
		// TraceId 本次请求的 trace_id；与日志、X-Request-ID 头同源，用于反查链路。
		TraceId *string `json:"trace_id,omitempty"`
	} `json:"metadata,omitempty"`

	// Reason 机器可读的错误常量（如 `INVALID_PARAMS`、`DATABASE_ERROR`）。前端用它做分支判断。
	Reason *string `json:"reason,omitempty"`
}

// ListExamplesRes 分页查询的响应数据。
type ListExamplesRes struct {
	// Examples 当前页结果。
	Examples []Example `json:"examples"`

	// Total 满足查询条件的总条数（用于前端算总页数）。
	Total int64 `json:"total"`
}

// LivenessResponse liveness 探针响应。
type LivenessResponse struct {
	// Status 永远是 "ok"——探针硬编码成功。
	Status string `json:"status"`

	// Version 通过 ldflags 注入的构建版本号，用于快速确认"现在跑的是哪一版"。
	Version string `json:"version"`
}

// MeEnvelope defines model for MeEnvelope.
type MeEnvelope struct {
	// Code 业务错误码。0 表示成功；非 0 详见 `pkg/errcode` 与 `docs/errcodes.md`。
	Code int `json:"code"`

	// Data 当前已鉴权主体信息。
	Data *MeRes `json:"data,omitempty"`

	// Message 人读的默认英文文案；按 reason 查 `pkg/response.MessageFor` 表。
	Message string `json:"message"`

	// Metadata 附加元信息。
	Metadata *struct {
		// TraceId 本次请求的 trace_id；与日志、X-Request-ID 头同源，用于反查链路。
		TraceId *string `json:"trace_id,omitempty"`
	} `json:"metadata,omitempty"`

	// Reason 机器可读的错误常量（如 `INVALID_PARAMS`、`DATABASE_ERROR`）。前端用它做分支判断。
	Reason *string `json:"reason,omitempty"`
}

// MeRes 当前已鉴权主体信息。
type MeRes struct {
	// Subject 从 Bearer token 解析出的 subject。
	Subject string `json:"subject"`
}

// BadRequest 错误响应信封。结构与 Envelope 一致，但 `data` 永远为空。完整的
// code / reason 目录见 `docs/errcodes.md`。
type BadRequest = ErrorEnvelope

// Forbidden 错误响应信封。结构与 Envelope 一致，但 `data` 永远为空。完整的
// code / reason 目录见 `docs/errcodes.md`。
type Forbidden = ErrorEnvelope

// InternalError 错误响应信封。结构与 Envelope 一致，但 `data` 永远为空。完整的
// code / reason 目录见 `docs/errcodes.md`。
type InternalError = ErrorEnvelope

// NotImplemented 错误响应信封。结构与 Envelope 一致，但 `data` 永远为空。完整的
// code / reason 目录见 `docs/errcodes.md`。
type NotImplemented = ErrorEnvelope

// RequestTimeout 错误响应信封。结构与 Envelope 一致，但 `data` 永远为空。完整的
// code / reason 目录见 `docs/errcodes.md`。
type RequestTimeout = ErrorEnvelope

// ServiceUnavailable 错误响应信封。结构与 Envelope 一致，但 `data` 永远为空。完整的
// code / reason 目录见 `docs/errcodes.md`。
type ServiceUnavailable = ErrorEnvelope

// TooManyRequests 错误响应信封。结构与 Envelope 一致，但 `data` 永远为空。完整的
// code / reason 目录见 `docs/errcodes.md`。
type TooManyRequests = ErrorEnvelope

// Unauthorized 错误响应信封。结构与 Envelope 一致，但 `data` 永远为空。完整的
// code / reason 目录见 `docs/errcodes.md`。
type Unauthorized = ErrorEnvelope

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListExamplesParams defines parameters for ListExamples.
type ListExamplesParams struct {
	// Limit 分页大小。默认 20；省略或传 0 时回退到默认。
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset 分页偏移（跳过的行数）。从 0 开始。
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateAuthTokenJSONRequestBody defines body for CreateAuthToken for application/json ContentType.
type CreateAuthTokenJSONRequestBody = CreateTokenReq

// CreateExampleJSONRequestBody defines body for CreateExample for application/json ContentType.
type CreateExampleJSONRequestBody = CreateExampleReq

// EnqueueExampleTaskJSONRequestBody defines body for EnqueueExampleTask for application/json ContentType.
type EnqueueExampleTaskJSONRequestBody = EnqueueExampleTaskReq

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 返回当前 Bearer token 的 subject
	// (GET /api/v1/auth/me)
	GetAuthMe(c *gin.Context)
	// 签发示例 JWT（仅开发环境）
	// (POST /api/v1/auth/token)
	CreateAuthToken(c *gin.Context)
	// 列出示例（按创建时间倒序）
	// (GET /api/v1/examples)
	ListExamples(c *gin.Context, params ListExamplesParams)
	// 创建一个示例
	// (POST /api/v1/examples)
	CreateExample(c *gin.Context)
	// 投递一个示例异步任务到 Asynq
	// (POST /api/v1/examples/tasks)
	EnqueueExampleTask(c *gin.Context)
	// 就绪探针（依赖健康检查）
	// (GET /health)
	GetHealth(c *gin.Context)
	// 存活探针
	// (GET /livez)
	GetLivez(c *gin.Context)
	// 返回原始 OpenAPI 3.1 spec
	// (GET /openapi.json)
	GetOpenAPISpec(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAuthMe operation middleware
func (siw *ServerInterfaceWrapper) GetAuthMe(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAuthMe(c)
}

// CreateAuthToken operation middleware
func (siw *ServerInterfaceWrapper) CreateAuthToken(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateAuthToken(c)
}

// ListExamples operation middleware
func (siw *ServerInterfaceWrapper) ListExamples(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListExamplesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListExamples(c, params)
}

// CreateExample operation middleware
func (siw *ServerInterfaceWrapper) CreateExample(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateExample(c)
}

// EnqueueExampleTask operation middleware
func (siw *ServerInterfaceWrapper) EnqueueExampleTask(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.EnqueueExampleTask(c)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GetLivez operation middleware
func (siw *ServerInterfaceWrapper) GetLivez(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLivez(c)
}

// GetOpenAPISpec operation middleware
func (siw *ServerInterfaceWrapper) GetOpenAPISpec(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOpenAPISpec(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/v1/auth/me", wrapper.GetAuthMe)
	router.POST(options.BaseURL+"/api/v1/auth/token", wrapper.CreateAuthToken)
	router.GET(options.BaseURL+"/api/v1/examples", wrapper.ListExamples)
	router.POST(options.BaseURL+"/api/v1/examples", wrapper.CreateExample)
	router.POST(options.BaseURL+"/api/v1/examples/tasks", wrapper.EnqueueExampleTask)
	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.GET(options.BaseURL+"/livez", wrapper.GetLivez)
	router.GET(options.BaseURL+"/openapi.json", wrapper.GetOpenAPISpec)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1HtrUxrZuv9XWcX//2LiNoK3fU48NbXLjMwZs41mK5k5+2xS0oGOYQe6SdOk4p6yClQUDIhJ8BI0GjLe",
	"JolALiqBNnyXSa/VzSu+wqm1VoMNNDEzZ+LUqUpVpLtZ/dwvv+fhR5OT9/p4juVEv6nvR5PA+n0852fJ",
	"h8uMa5S9G2D9Iv7k5DmR5cifjM/ncTsZ0c1z5n/6eQ5f8ztvs14G//X/BfaWqc/0/8ynR5vpXb/ZKgi8",
	"YOXusR7ex5qmpqbaTS7W7xTcPnyYqc8EM89R5Fh5mS0nn6jZbEWKdN6/fx+gzGFFin4MTsN8Xt0LVaSU",
	"Y3D4+/6hwYHxa/2j/VfHHOCrToul8wKAiWm0nEPP0uUXMbj9Wn238zE4bedu8q5JIJfSMBeC+V3lzQcl",
	"nVFSs8AhsIyf5xzADBxO3sU6KlKsRgOKZ9DBNozMoWQWRrbRygE5yzTVbvqWF266XS6WO0fRHL8pR9+h",
	"pzPyyRxafYaezpSfLH0MTmssfH3NOnp1cGxscGR4fMA6PGgdcFSkCOYJdFos3VR8lPhBTmQFjvGQV54f",
	"A2gjDhfSysssDG/AwnJNw5fqNKzuzinrK8AxOGyzjg73D41bR0dHRh3gq0tYvx+DITvnGOi39V/uH7Pq",
	"73Xhe46/Xbder7vccwEoB6esD/PioNfnYb0sJ7Ku8+NdeZlVpt/D4zfqbApFH6DNIyW5hSJL8smcnE/B",
	"hXQ5WFQ/PEQbL2BmU1nM6fQ6PGIbH7x6bch61Tpssw6M/91qq2n2ksXSq9es5q82t5flA+fotmr2GL2e",
	"htuzytKcehRWS/PlcFw5IS5WT5OOsVHr365bx2zjtsGr1pHrNr251jE1xgr33E72OsfcY9we5qaHPT/G",
	"5PwDlM/LH56qhytyPg4TWSW5jyIrVJ/q85eUTygFYfgtDL8trx7obJha4/Xh/u/7B4f6Lw9ZqU12X7Bz",
	"cn4ROMaso98PfmMdHxgcw3cHaBT784VfgslfgkkYjavBsJreV7YLlAKUmkarRyg2LRfmPgZDMJEtz8fV",
	"7HJFWodLi2owbOfo45QqFAxVSQrRB9HqMyW5j+NoNcYpyX1AgmMtEsJYAUbmatK38fxVhpvUtOg/R5va",
	"24WJh+UnS+gwpLMa28jI+NX+4b+Pa+YzprebHr3dXOeYgHibF9z/Ok9PpzGaph5sKFIB5h7C+QM1G6pI",
	"EZG/w3IAX9x+DcxALc2jjS1gBsrBB7gUx2F9OVLlocrx9eH+67bvRkYH/7s+pnedMjvVrpFP9PONwDIi",
	"a73P4Eg3yt7F1xpySWQdFgvErh4oqVnqvvLJ44/BaVO7ySfwPlYQ3bQM4Bgva3DCUlzZy1WkdeoVcr6g",
	"/FyoSDG0ESwvl0BXby89y8vcH2K5CfG2qa+rt7fd5HVz1c+d7SZx0sea+kx+UXBzE4QNgb0bcAtYYf+g",
	"b75Re4q/+U/WKWLNUgZtWJY1VWCtejwjt0x9/zhDgzXltf/YwKqLEc80AN27R1k/obmBvhv1FBoqAOs7",
	"8ZAqAGhGcYYe/AF6ftNZ6m5IOfigltZPDwLawxUpUg6mYD6P1mjgOgaDAwCbJfkAl+LUhvRK1PT2K/RU",
	"pewMVY2y/mbiqSBQZAkubKmlJFzfxORTRnAhF88YyYJxOlm/f5w81nzmd2NdvX/WXAqfduUHmz7koYUF",
	"mJlBSSIyR78WI0gw6AOXWUZgBWAPWCzdTnI++ZN1ALj9jpLSIIx2E3lsnF5u8pP1Asyk5HwB2E30bLuJ",
	"HsNyAS+WHr1qutF0cIOU63iue6mR3K3c3QAbqAYBG+O/c+6e0kzCJxzG6GEDv0ELy+XgIyhNo4MduVjE",
	"9eRvCl/0u8T+I7QAU+dfYEW9j1akaEVaLy+XYGEXdF78spHMWEYt2FaKj9HmhhGT5BBX8/dEIcCCrwE8",
	"fkM9DIZ3ymtbhOe4XPxJTe/jW9E9NR2jgeDUvG/yvIdluCZWtFcZM3NqYQ1eXtyS80H4OA4LSdqFfQxO",
	"U5Jo39UHLA5cxZC0CfO75aebwEJvOT4GQ8r+W5hJndYocv6NnYOPYrgCCkZJI+dlRQZbZYcoME523O3C",
	"rRxaeS9/KMFonLj9Tnk1U36+hlaPlOITuLSIW5FMSj6Jo9UdWFqlubRRtJgEA/uhRTtpYZRnmBsLoKUX",
	"5QpbEGFBze6qeyHg8N2ZMLOCQBgCpPhz8U5/9ZK/w+ty1InfzYnsBCtgsXpZv5+ZMCKiUFCzRSU1Wy6u",
	"qZlt9cFrtDKP/6UjFWkdxaKAygugrR1KQbW/77hKz/yWFxyY7haBrSrT5leXn8zChWcwPCOX0iiUNbLJ",
	"qh4MrHnjFXqVpl5Lor32JKkmFqvKCP3XRa3ovDg4gKMvXIqhwlJFiinJfbmwCBNxtLVTfvxBPc4a0j9l",
	"YKJUIEYkFeCTfZjIagIlioX5fHk+UZEicHcaNAIOuNts6EM1iIJYm5Lch5kZGEo1wAems0IFsbdTpRv6",
	"WV0N+hvC+Y2mopXyW++fJNzMYlutfhPI+aA6/64ixeSTOeDApuEAKJdXSxu12gFmYmj5nZKatXOkUDVX",
	"jVBZz8CTZeIMRqZPa3YtEBpEEFIqqYezqLAEM5stgr2TVBuucUZsVfOi1aPy6ruKFBn99pvu7u5LFSl2",
	"3fZNLfjd4gUv/jJOcOxF0e1ljfzCyKjlfLGczGD4KL6s5mZwlnq+2XComxP/3EOLK7c34NUnDp2/n1Fw",
	"6zMT1kR+EQxcBo57jOC8zQhfdfX2XnAAmH1fPllq4dYBn6ullNBGUC09lPNB9CqN1t+hldzvILEGE3e7",
	"TBqX7XqN1RFmaPfUOM6/kNGMskXp8h3LeMTbo1pobRapwDIuN8f6/QAtPi8/ilA3MzLfmwG3xyhebs5i",
	"y93YqsXbihTxuG55mAk/QG/3YXhHw84yPyvrD9HinrL+Di3uyMVFYL5NqANo4bESjaCNVzBxTKwmDkth",
	"Owfn4jC+rDx4BaWgnA/K+Rf0KYpvGGdEQuU40XQrUonJoMjbllbTZJNO3ut1G9ijsnUA6D0w9l1/iy/f",
	"YwW/2yisq9kD+X0UxlZqvKPIChCZCQCX4p8Tjasn1whs17NvZKTO26zzDm1SXC43poPxXKuTX7Xw5+9g",
	"k9ehWu0mjhfHnTx3yz0REOqKrFNeG+SdTcj5FxQdUlKzMLQDC8fKwhEKhipS7A47CdBalt6mxa6P94sT",
	"Ausncdnlxv8z/knuLkZJG7VzypRfZMSAQV3K3+kDMLxfntnX3pHIqh8+VKR1FzshMC7W1QfKTzcxCJXM",
	"0CewReD3VqQolDCcX5Fi39ls14BcjIMui6Uixezc0GUg5+Po4Ro6DFWk9QBHjXiyDzQcdU3jpum0Xox4",
	"x4YuA3pI1ZDrRF+lkWhBe8PZbZgmipqiNYMwtIUht1/Ugof/3KOW/uWfaLwaHzPIm3Pl9CHa2lGzz7GJ",
	"kejVujVntbMMDjp5DKPxcvpQ38e4Rdbr/+wAXOOAEQRmknzmRcZjEIeKafXoLSUaPU3LxSMlNYuCRfQ0",
	"jZZzFSmi1ZC0VsusomARM7mcq/lA66RtaU7aDTZSk0GVPmPjuMfirNA6cXi0J87MG63ck5ZmaC0L7Cb+",
	"jt1EcWV6mpJ+pUgryrMQbVjosWy1/KIe8vmBthxMqaV5UJ+UsMhJPtBnHk3wpZfl4JaSzqiZbbtJWczB",
	"jX31+CH+xloWPn4h54NKNFKFSj7TI6vUGUn76vmXDVfZT7gdvdnCR05HffmifPK4dY/VEhPEqV+DsiiW",
	"pu79hDaX4HxBhw5+lnBbYns4LbDOgOAWJ8cwx1pxQF6KQbXTT99WXenKDzaThlQTiIHcPSXhtij6KKTu",
	"5m7xVcieofzRqtg0wV/032E9rMhzzdlQdxNo08bULJwLl2f2Qf+1QQB3HiqFXZIM7JxS2IWZVEVK2bmL",
	"gPbz1MMoWCGflPBsxPEjblLagdaPtWvdzF/aATaBv7SDao/8lykHqLVOdg5Q8AJ8DSwOY2SA3Ma+WY8N",
	"UBBKSc1SzKMBaMAHV4fiTbPyGJ2kVses1ct0SHARkMRInQVgcED/3g7SU3bgR8bIE19dcAC09gzmZul4",
	"CD9EZAWAhtv8MveIJux1Qg3+2GOxmHssneYeS7e5x9Jj7rH8u7mn65KZZOP1S9XHei0Wc6+lE1/WZFVj",
	"BfefxR3gwO/s0AQSStF5vaYj0klXpHU9OzDxQj4hPSgpfz8GQ0OXyagYgHIwgdYW5eJPytIc1SmW7ZtV",
	"5c0jWNjFGkscawKCWwUlHVQzH9DKCS2AgcOMg/C/NMhGK6bxp7h6mKMEUaXjyEaKbgpiY8lg/oBSfIKp",
	"+GvgJitwrMhWgzklpVqXiG7R02Dd2GB1Ma3PZOno7LBgm+d9LMf43KY+Uze51G7yMeJt4n1mxuc23+s0",
	"48GXmdbnE6xRl0f2I34d+F2RYhpvn4wodu5zZlxo9UgtJUGPpbMiRRwNE65oVSw41BHSBl2mPtN/siKm",
	"9youlOsWVboslt9tvqfLE4bjYL3G12nWo8JEq0cUEenQZOEAaKkA87s0pNNIjiPuVLupx9LZio4aY+a6",
	"8eVUu6nXYjn7S/WrHfoYTbKdPjr/4wbGgfwBr5cRJnGvRJRLqa3PHToFY1tlJvxkHoFPuYFfUWd1tZkM",
	"7jQMOrLjrJJ83dYG9x4oxUhbG64U5mJ4vnvlB9v4mPWbUavNgQFrOsKW80ngwMYxPmD9ftw28lfr8Lh1",
	"mAzLv8bgtsPOYTiXDJEAnfsQAshEfBdGnqilpF5pNCp/jafsZOdHG7E2DeJJG9K4CEQG43ZtlwN30Adr",
	"cGPfbpLzi9Wr6vOXMPyW1C1tbUpySy7sKYtZ+HwGlsLldLG2IdDWZmDgdFaGtWPThjwCBUAv867J383C",
	"G0aTRssqRJx0k4rWCKcVARb61Bf0P6PR7tmOSFNSzQUdAB6soswhdUBqETXX+wwv0m2+/UbHw9/qPvtb",
	"BqstU1N6p6ybE1/5wYZHN8UwXjdJPKSGVZGin3RKfT9mmAvq+js9yhpZpZMBfWCgTRKKZ8CfgL6dcpA+",
	"x0FmZ6cLdHaOeo6aSet7LGL/UCpQNBkF9wD5dltbRUrRak09zAHHKOtjGRELZZRlXOBPAP83wnkmHXZO",
	"LjyAC2kMZJWeqtkQ8Lj9IoCPYvQkgJ7u4HneUgxPnUovlTAuCfDMS0pREmAWO7CcXzBONfqmmORXgfGy",
	"Iiv4SRQ1kh/c3oO5xMfgNJ3FgC5cGCkbIWUZb4HI0jNgAWj1CK5vloNBGMnRx7QeGB9zN8AKk1VcFPd+",
	"FG069Rovc18DjS2WT0PIU+0taAwllL1iRYqox2/V0jyenKZjtZ4XtwwWgE1r70Fruvhbt/xsA2Gfaoxv",
	"fMFYYQivnB0sDEIE2nhVh0ucX6Co83YYWcX1FHHCihRBsah+aAGDj2AhUe/v1YYdt5TGCRdu7AOH9pif",
	"tCIo8QiGdzDE/zStZnLwZBmnX6zfqlDwd266OZebmwDltSN8JZSiZY6dwzslzSOI6hs68DkARlaNJxI0",
	"QKhH4fJyqVYv27nG4RpFqGUpBSM5PN2Ar6eNHbVu1emLJkzdOpXRci7R0x+TMhvHIr/NA1ZyGKhJzdLg",
	"/4c6ARalNowgrmBo7wYpziwyfgq9G7sCWljQ9j7Sm3j3p58A3+W1Lex3ZKWErkJ8DE6Patg4fQRtvNA2",
	"KknbYucMNjt1K7nd1MqrQLS2zVlrcRO1xXLcyaK1rJ2zm5oXPO0mtbSG97Y2tvDAkza/pxvtTa7QvEry",
	"hfzBeFXHyOqosP8Yp2i9//Sry8kOcpQLt/0FgAn/v1lL0iUivWPp96hwpCXW3tLbKPjRso7EyAoxVQo0",
	"0SGU8gxvvXZZLMBMZzJRpfgEkPnOoh4UwfnlMFSeT8C5t8rBCtk+eGLnGkenSnJf8ybiCLKUUjM/g9qY",
	"Rz6Za2uT8/G2tvJ8HC5lgY934ZUEAutpd9TDnJ3TIL4qclNDuLSQWOvtWgIRdOb7JYGIhqlyy99T0JEf",
	"3nWKBtFGFJbC6m5IP43TjFWzoXOijVoZiqzA7ZScf6GnqrZGTwirD/2510rxBVU17nQoF4RB9FMQbe3U",
	"Fz+aQVLrJDhdS+NUS+vK/gM8ZCgtqekYzL2msxEMQnVZLNTe9AbZMHtpNjxqYXbOx7twy7P+DB1sExNT",
	"Z07a2jRWi0X5ZBlur5Rn9pW3RaWIV+8GLgMzoPmlNnM1NrIhwtIXLaAbRlBGa/hUcgdr6F3RQGPkOpVR",
	"K81oeGVHlTZDBWHU98rYyDCAJ8+hlNB6zrkwPIxh+GnEx3IYwe/u6ATq3qwam8F+ncjCrATDOwDPgb0M",
	"B8zgshDgeGC2c4Ocn/dybgYLGf8qZe+n2iF4KHC8A8PHuEdc2Ke/xKnlZ2AGXt55p6VWtFPGfKzzf6sb",
	"4w0BnGGapy1NitGLxO9jnc3K0YS4uAX3HoDGx3XawiMMrCv8ZVa4Z9zmDvFOxgNcLEmi+OdT4Cu318cL",
	"InCxt5iAR/wPYMZ7XYC/xwqC28X6ASMCIcDhTYkLeMYueLQZT5/Z3Nn1bx2WDktHZ1+3xWIhG2kaNY3v",
	"1bt/bSulBst/2mtxD6V3c+yoxH/tXM2DAXFgvPJ7Cu/jUxtTTy0e1eIXPrRhzwD/ridOz9U5ttY6a07R",
	"3J1f+cEG6LyPpmXC4CmY6gByMayNTXXAT/NPCMhYG0OOFGakXNk5R3Uc4AD0FO3XkQZIL3x/pGH8ekD/",
	"lAUmYMiAHjbCmUhKKtsFughItzzJHkdK/9tMMgjy05JFm76RSwLr4/1ukRcmgbp0AguP7Ry+bLxAvJJD",
	"+2n4dFUJ76kPX6oLu0qyqDx+DuNvYSLbQDpb2yFopJ5MBqubVdTEKlKk6i/YV/Dw4nSEHdX/mABX8w+i",
	"9Cl9OMEDp2ehBhqIo03dmPqfAQA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
