// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for CreateTokenResTokenType.
const (
	Bearer CreateTokenResTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the CreateTokenResTokenType enum.
func (e CreateTokenResTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseChecks.
const (
	HealthResponseChecksNotConfigured HealthResponseChecks = "not_configured"
	HealthResponseChecksOk            HealthResponseChecks = "ok"
	HealthResponseChecksUnavailable   HealthResponseChecks = "unavailable"
)

// Valid indicates whether the value is a known member of the HealthResponseChecks enum.
func (e HealthResponseChecks) Valid() bool {
	switch e {
	case HealthResponseChecksNotConfigured:
		return true
	case HealthResponseChecksOk:
		return true
	case HealthResponseChecksUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusDegraded  HealthResponseStatus = "degraded"
	HealthResponseStatusOk        HealthResponseStatus = "ok"
	HealthResponseStatusUnhealthy HealthResponseStatus = "unhealthy"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case HealthResponseStatusDegraded:
		return true
	case HealthResponseStatusOk:
		return true
	case HealthResponseStatusUnhealthy:
		return true
	default:
		return false
	}
}

// CreateExampleReq 创建示例的请求体。
type CreateExampleReq struct {
	// Name 名称；不可为空，最长 255。
	Name string `json:"name"`
}

// CreateTokenEnvelope defines model for CreateTokenEnvelope.
type CreateTokenEnvelope struct {
	// Code 业务错误码。0 表示成功；非 0 详见 `pkg/errcode` 与 `docs/errcodes.md`。
	Code int `json:"code"`

	// Data 签发成功返回的 token 数据。
	Data *CreateTokenRes `json:"data,omitempty"`

	// Message 人读的默认英文文案；按 reason 查 `pkg/response.MessageFor` 表。
	Message string `json:"message"`

	// Metadata 附加元信息。
	Metadata *struct {
		// TraceId 本次请求的 trace_id；与日志、X-Request-ID 头同源，用于反查链路。
		TraceId *string `json:"trace_id,omitempty"`
	} `json:"metadata,omitempty"`

	// Reason 机器可读的错误常量（如 `INVALID_PARAMS`、`DATABASE_ERROR`）。前端用它做分支判断。
	Reason *string `json:"reason,omitempty"`
}

// CreateTokenReq 签发示例 token 的请求体。
type CreateTokenReq struct {
	// Subject 要签进 token 的 subject（通常是用户 ID 或用户名）。不可为空。
	Subject string `json:"subject"`
}

// CreateTokenRes 签发成功返回的 token 数据。
type CreateTokenRes struct {
	// AccessToken HS256 签名的 JWT。客户端把它放进 `Authorization: Bearer <token>` 头。
	AccessToken string `json:"access_token"`

	// TokenType 固定为 "Bearer"。
	TokenType CreateTokenResTokenType `json:"token_type"`
}

// CreateTokenResTokenType 固定为 "Bearer"。
type CreateTokenResTokenType string

// EnqueueExampleTaskEnvelope defines model for EnqueueExampleTaskEnvelope.
type EnqueueExampleTaskEnvelope struct {
	// Code 业务错误码。0 表示成功；非 0 详见 `pkg/errcode` 与 `docs/errcodes.md`。
	Code int `json:"code"`

	// Data 投递结果。
	Data *EnqueueExampleTaskRes `json:"data,omitempty"`

	// Message 人读的默认英文文案；按 reason 查 `pkg/response.MessageFor` 表。
	Message string `json:"message"`

	// Metadata 附加元信息。
	Metadata *struct {
		// TraceId 本次请求的 trace_id；与日志、X-Request-ID 头同源，用于反查链路。
		TraceId *string `json:"trace_id,omitempty"`
	} `json:"metadata,omitempty"`

	// Reason 机器可读的错误常量（如 `INVALID_PARAMS`、`DATABASE_ERROR`）。前端用它做分支判断。
	Reason *string `json:"reason,omitempty"`
}

// EnqueueExampleTaskReq 投递异步任务的请求体。
type EnqueueExampleTaskReq struct {
	// Name 任务名（业务自定义）；长度 1-255。
	Name string `json:"name"`
}

// EnqueueExampleTaskRes 投递结果。
type EnqueueExampleTaskRes struct {
	// Queued true = 已成功入队（不代表已执行）。
	Queued bool `json:"queued"`
}

// Envelope 统一响应信封。成功 `code: 0`；失败带非 0 `code`、稳定 `reason` 串
// 和可选的 `metadata.trace_id`，方便前端报问题时给后端定位日志。
type Envelope struct {
	// Code 业务错误码。0 表示成功；非 0 详见 `pkg/errcode` 与 `docs/errcodes.md`。
	Code int `json:"code"`

	// Message 人读的默认英文文案；按 reason 查 `pkg/response.MessageFor` 表。
	Message string `json:"message"`

	// Metadata 附加元信息。
	Metadata *struct {
		// TraceId 本次请求的 trace_id；与日志、X-Request-ID 头同源，用于反查链路。
		TraceId *string `json:"trace_id,omitempty"`
	} `json:"metadata,omitempty"`

	// Reason 机器可读的错误常量（如 `INVALID_PARAMS`、`DATABASE_ERROR`）。前端用它做分支判断。
	Reason *string `json:"reason,omitempty"`
}

// ErrorEnvelope 统一响应信封。成功 `code: 0`；失败带非 0 `code`、稳定 `reason` 串
// 和可选的 `metadata.trace_id`，方便前端报问题时给后端定位日志。
type ErrorEnvelope = Envelope

// Example 示例资源实体。
type Example struct {
	// CreatedAt 创建时间（RFC3339，UTC）。
	CreatedAt time.Time `json:"created_at"`

	// Id 主键，单调递增。
	Id int64 `json:"id"`

	// Name 名称；长度 1-255，与 DB `varchar(255)` 对齐。
	Name string `json:"name"`

	// UpdatedAt 最近一次更新时间（RFC3339，UTC）。
	UpdatedAt time.Time `json:"updated_at"`
}

// ExampleEnvelope defines model for ExampleEnvelope.
type ExampleEnvelope struct {
	// Code 业务错误码。0 表示成功；非 0 详见 `pkg/errcode` 与 `docs/errcodes.md`。
	Code int `json:"code"`

	// Data 示例资源实体。
	Data *Example `json:"data,omitempty"`

	// Message 人读的默认英文文案；按 reason 查 `pkg/response.MessageFor` 表。
	Message string `json:"message"`

	// Metadata 附加元信息。
	Metadata *struct {
		// TraceId 本次请求的 trace_id；与日志、X-Request-ID 头同源，用于反查链路。
		TraceId *string `json:"trace_id,omitempty"`
	} `json:"metadata,omitempty"`

	// Reason 机器可读的错误常量（如 `INVALID_PARAMS`、`DATABASE_ERROR`）。前端用它做分支判断。
	Reason *string `json:"reason,omitempty"`
}

// HealthResponse readiness 探针响应。
type HealthResponse struct {
	// Build 构建期元信息（ldflags 注入）。让监控直接从 /health 抓版本号，不必
	// 再单独开一个版本端点。
	Build struct {
		// BuildTime 构建时间戳（RFC3339，UTC）。
		BuildTime string `json:"build_time"`

		// Commit 短 commit SHA。
		Commit string `json:"commit"`

		// Version 语义化版本号或 tag 名。
		Version string `json:"version"`
	} `json:"build"`

	// Checks 每个依赖的健康状态，key 是依赖名（postgres / redis / asynq 等）。
	Checks map[string]HealthResponseChecks `json:"checks"`

	// Status ok: 全部依赖可达；degraded: 非关键依赖（Redis）异常，HTTP 仍 200，
	// LB 不摘流；unhealthy: 关键依赖（Postgres）异常，HTTP 503，LB 摘流。
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseChecks defines model for HealthResponse.Checks.
type HealthResponseChecks string

// HealthResponseStatus ok: 全部依赖可达；degraded: 非关键依赖（Redis）异常，HTTP 仍 200，
// LB 不摘流；unhealthy: 关键依赖（Postgres）异常，HTTP 503，LB 摘流。
type HealthResponseStatus string

// ListExamplesEnvelope defines model for ListExamplesEnvelope.
type ListExamplesEnvelope struct {
	// Code 业务错误码。0 表示成功；非 0 详见 `pkg/errcode` 与 `docs/errcodes.md`。
	Code int `json:"code"`

	// Data 分页查询的响应数据。
	Data *ListExamplesRes `json:"data,omitempty"`

	// Message 人读的默认英文文案；按 reason 查 `pkg/response.MessageFor` 表。
	Message string `json:"message"`

	// Metadata 附加元信息。
	Metadata *struct {
		// TraceId 本次请求的 trace_id；与日志、X-Request-ID 头同源，用于反查链路。
		TraceId *string `json:"trace_id,omitempty"`
	} `json:"metadata,omitempty"`

	// Reason 机器可读的错误常量（如 `INVALID_PARAMS`、`DATABASE_ERROR`）。前端用它做分支判断。
	Reason *string `json:"reason,omitempty"`
}

// ListExamplesRes 分页查询的响应数据。
type ListExamplesRes struct {
	// Examples 当前页结果。
	Examples []Example `json:"examples"`

	// Total 满足查询条件的总条数（用于前端算总页数）。
	Total int64 `json:"total"`
}

// LivenessResponse liveness 探针响应。
type LivenessResponse struct {
	// Status 永远是 "ok"——探针硬编码成功。
	Status string `json:"status"`

	// Version 通过 ldflags 注入的构建版本号，用于快速确认"现在跑的是哪一版"。
	Version string `json:"version"`
}

// MeEnvelope defines model for MeEnvelope.
type MeEnvelope struct {
	// Code 业务错误码。0 表示成功；非 0 详见 `pkg/errcode` 与 `docs/errcodes.md`。
	Code int `json:"code"`

	// Data 当前已鉴权主体信息。
	Data *MeRes `json:"data,omitempty"`

	// Message 人读的默认英文文案；按 reason 查 `pkg/response.MessageFor` 表。
	Message string `json:"message"`

	// Metadata 附加元信息。
	Metadata *struct {
		// TraceId 本次请求的 trace_id；与日志、X-Request-ID 头同源，用于反查链路。
		TraceId *string `json:"trace_id,omitempty"`
	} `json:"metadata,omitempty"`

	// Reason 机器可读的错误常量（如 `INVALID_PARAMS`、`DATABASE_ERROR`）。前端用它做分支判断。
	Reason *string `json:"reason,omitempty"`
}

// MeRes 当前已鉴权主体信息。
type MeRes struct {
	// Subject 从 Bearer token 解析出的 subject。
	Subject string `json:"subject"`
}

// BadRequest 错误响应信封。结构与 Envelope 一致，但 `data` 永远为空。完整的
// code / reason 目录见 `docs/errcodes.md`。
type BadRequest = ErrorEnvelope

// Forbidden 错误响应信封。结构与 Envelope 一致，但 `data` 永远为空。完整的
// code / reason 目录见 `docs/errcodes.md`。
type Forbidden = ErrorEnvelope

// InternalError 错误响应信封。结构与 Envelope 一致，但 `data` 永远为空。完整的
// code / reason 目录见 `docs/errcodes.md`。
type InternalError = ErrorEnvelope

// NotImplemented 错误响应信封。结构与 Envelope 一致，但 `data` 永远为空。完整的
// code / reason 目录见 `docs/errcodes.md`。
type NotImplemented = ErrorEnvelope

// RequestTimeout 错误响应信封。结构与 Envelope 一致，但 `data` 永远为空。完整的
// code / reason 目录见 `docs/errcodes.md`。
type RequestTimeout = ErrorEnvelope

// ServiceUnavailable 错误响应信封。结构与 Envelope 一致，但 `data` 永远为空。完整的
// code / reason 目录见 `docs/errcodes.md`。
type ServiceUnavailable = ErrorEnvelope

// TooManyRequests 错误响应信封。结构与 Envelope 一致，但 `data` 永远为空。完整的
// code / reason 目录见 `docs/errcodes.md`。
type TooManyRequests = ErrorEnvelope

// Unauthorized 错误响应信封。结构与 Envelope 一致，但 `data` 永远为空。完整的
// code / reason 目录见 `docs/errcodes.md`。
type Unauthorized = ErrorEnvelope

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListExamplesParams defines parameters for ListExamples.
type ListExamplesParams struct {
	// Limit 分页大小。默认 20；省略或传 0 时回退到默认。
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset 分页偏移（跳过的行数）。从 0 开始。
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateAuthTokenJSONRequestBody defines body for CreateAuthToken for application/json ContentType.
type CreateAuthTokenJSONRequestBody = CreateTokenReq

// CreateExampleJSONRequestBody defines body for CreateExample for application/json ContentType.
type CreateExampleJSONRequestBody = CreateExampleReq

// EnqueueExampleTaskJSONRequestBody defines body for EnqueueExampleTask for application/json ContentType.
type EnqueueExampleTaskJSONRequestBody = EnqueueExampleTaskReq

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 返回当前 Bearer token 的 subject
	// (GET /api/v1/auth/me)
	GetAuthMe(c *gin.Context)
	// 签发示例 JWT（仅开发环境）
	// (POST /api/v1/auth/token)
	CreateAuthToken(c *gin.Context)
	// 列出示例（按创建时间倒序）
	// (GET /api/v1/examples)
	ListExamples(c *gin.Context, params ListExamplesParams)
	// 创建一个示例
	// (POST /api/v1/examples)
	CreateExample(c *gin.Context)
	// 投递一个示例异步任务到 Asynq
	// (POST /api/v1/examples/tasks)
	EnqueueExampleTask(c *gin.Context)
	// 就绪探针（依赖健康检查）
	// (GET /health)
	GetHealth(c *gin.Context)
	// 存活探针
	// (GET /livez)
	GetLivez(c *gin.Context)
	// 返回原始 OpenAPI 3.1 spec
	// (GET /openapi.json)
	GetOpenAPISpec(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAuthMe operation middleware
func (siw *ServerInterfaceWrapper) GetAuthMe(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAuthMe(c)
}

// CreateAuthToken operation middleware
func (siw *ServerInterfaceWrapper) CreateAuthToken(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateAuthToken(c)
}

// ListExamples operation middleware
func (siw *ServerInterfaceWrapper) ListExamples(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListExamplesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListExamples(c, params)
}

// CreateExample operation middleware
func (siw *ServerInterfaceWrapper) CreateExample(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateExample(c)
}

// EnqueueExampleTask operation middleware
func (siw *ServerInterfaceWrapper) EnqueueExampleTask(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.EnqueueExampleTask(c)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GetLivez operation middleware
func (siw *ServerInterfaceWrapper) GetLivez(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLivez(c)
}

// GetOpenAPISpec operation middleware
func (siw *ServerInterfaceWrapper) GetOpenAPISpec(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOpenAPISpec(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/v1/auth/me", wrapper.GetAuthMe)
	router.POST(options.BaseURL+"/api/v1/auth/token", wrapper.CreateAuthToken)
	router.GET(options.BaseURL+"/api/v1/examples", wrapper.ListExamples)
	router.POST(options.BaseURL+"/api/v1/examples", wrapper.CreateExample)
	router.POST(options.BaseURL+"/api/v1/examples/tasks", wrapper.EnqueueExampleTask)
	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.GET(options.BaseURL+"/livez", wrapper.GetLivez)
	router.GET(options.BaseURL+"/openapi.json", wrapper.GetOpenAPISpec)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Fv7UxpZvv9XTnHvDxPXCL7m3nhraktHZsesj6ySmbt3SUkHOoaNdJOmScWdsgpUFAyoSfARNBoSH2wS",
	"wcSoBNrwv6x9Tjc/8S/cOuc02EATs3M3Tt2qVEW6m9Pfx+f7/vKLycl7vDzHcqLP1PWLSWB9Xp7zseRD",
	"D+MaZu/7WZ+IPzl5TmQ58ifj9Y67nYzo5jnzX308h6/5nHdZD4P/+neBvWPqMv2b+fxoM73rM1sFgRes",
	"3AN2nPeypsnJyWaTi/U5BbcXH2bqMsH0SxQ+Ud5kivFnaiZTksKtDx8+BCh9VJIiZ4EpmM2qe8GSlHD0",
	"Df7U3d/XO3qje7h7YMQBvmm1WFqvALg4hZYP0Itk8XUUbr9TP+ycBabs3G3eNQHkQhIeBGF2V3n/SUmm",
	"lcQMcAgs4+M5BzADh5N3sY6SFK3QgGJptL8Nw7MonoHhbbSyT84yTTabfuCF226Xi+UuUTQn74uRD+j5",
	"tHw6i1ZfoOfTxWdLZ4EpjYXvbliHB/pGRvqGBkd7rYN91l5HSQpjnkCrxdJOxUeJ7+NEVuCYcfLKy2MA",
	"bcTgfFJ5k4GhDZhbrmj4WpWG1d1ZZX0FOPoGbdbhwe7+Uevw8NCwA3xzDev3LBC0c47eblt3T/eIVX+v",
	"Dd9z/Omm9WbV5Y4rQNk/Z32QF/s83nHWw3Ii67o83pU3GWXqIzx5r84kUOQR2jxW4lsovCSfzsrZBJxP",
	"FgN59dNjtPEapjeVhQOdXgeHbKN9Azf6rQPWQZu1d/TPVltFs9cslk69ZjV7tbk9LO+/RLNVMyfo3RTc",
	"nlGWZtXjkFqYK4ZiyikxsWqadIwNW/900zpiG7X1DViHbtr0cK1iaoQVHrid7E2OecC4x5nb4+zlMSZn",
	"H6FsVv70XD1akbMxuJhR4ikUXqH6VF++oXxCKQBDhzB0WFzd12GYovHmYPdP3X393T39VorJ9it2Ts4u",
	"AMeIdfinvu+to719I/huL/Vi3175RyD+j0AcRmJqIKQmU8p2jlKAElNo9RhFp+Tc7FkgCBczxbmYmlku",
	"SetwaUENhOwcfZxShQLBMklB+iBafaHEU9iPln2cEk8B4hwrnhBGczA8W5G+jecHGG5C06LvEjG1twsX",
	"HxefLaGjoA41tqGh0YHuwT+PavAZ0eOmQ4+bmxzjF+/ygvtvl2np1EfT0IOBIuXgwWM4t69mgiUpLPL3",
	"WA7gi9vvgBmohTm0sQXMQNn/BJdi2K0vh8s8lDm+Odh90/bj0HDf/1T79LZzZiebNfKJfr4XWEZkrQ8Z",
	"7OmG2fv4Wk0sCa/DfI7g6pGSmKHmK58+PQtMmZpNXoH3soLopmkAx3hYgxOWYsreQUlap1YhZ3PK33Ml",
	"KYo2AsXlAmjr7KRneZiH/Sw3Jt41dbV1djabPG6u/Lm12SROeFlTl8knCm5ujLAhsPf9bgEr7C/0zbcq",
	"T/G3/8o6RaxZyqANy7KiCqzV8fGhO6auv1ygwYrymn+pYdXFiBcCQPfuYdZHaK6h71Y1hYYKwPpefEwV",
	"ADRQXKAHn5+eX3eWuhtU9j+phfXzg4D2cEkKFwMJmM2iNeq4TkBfL8CwJB/gUoxiSK9ETW//hJ7KlF2g",
	"qmFNyAaCQOElOL+lFuJwfROTTxnBiVwsbSQLxulkfb5R8lj9mT+OtHV+q5kUPu36zza9y0Pz8zA9jeJE",
	"ZI5uzUcQZ9AFelhGYAVg91ss7U5yPvmTdQC4/YGSUiOMZhN5bJRerrOT9RxMJ+RsDthN9Gy7iR7Dcn4P",
	"lh69qhNeAylX8Vz1UiO5W7n7ftZfdgI2xnfv0i2lnoTPGIzRwwZ2g+aXi4EnUJpC+ztyPo/zyV/lvuh3",
	"Cf7DNAFT515jRX2MlKRISVovLhdgbhe0Xv26nsxYRg3YVvJP0eaGEZPkEFf990TBz4LvADx5Ty0MhnaK",
	"a1uE55icf6UmU/hWZE9NRqkjOIf3bZ4fZxmujhXtVcbMnCOsxsrzW3I2AJ/GYC5Oq7CzwBQlidZdXcDi",
	"wFkMCZswu1t8vgksWkl2FggqqUOYTpznKHL2vZ2DT6I4AwpESCHnYUUGo7JFFBgnO+p24VIOrXyUPxVg",
	"JEbMfqe4mi6+XEOrx0r+GVxawKVIOiGfxtDqDiys0lhaK1pMggF+aNJOShjlBebGAmjqRbnCCCIsqJld",
	"dS8IHN57Y2ZWEAhDgCR/Lt7pK1/ytXhcjirxuzmRHWMFLFYP6/MxY0ZE5HJqJq8kZor5NTW9rT56h1bm",
	"8L9kuCSto2gEUHkBtLVDKSjX9y0D9MwfeMGB6W7g2MoyrX918dkMnH8BQ9NyIYmCGSNMlvVggOaNt+ht",
	"klot8fbakySbWCgrI/jfV7Wk82pfL/a+cCmKckslKarEU3JuAS7G0NZO8ekn9SRjSP+kAUSpQIxIysFn",
	"KbiY0QRKFAuz2eLcYkkKw90pUNtwwNVmTR2qtSgI2pR4CqanYTBR0z4wXeQqCN7OlW5oZ1U56K9w57fq",
	"klbKb7V9Enczg7Fa/iaQswF17kNJisqns8CBoeEA6CCrFjYquQNMR9HyByUxY+dIomoug1BZT8PTZWIM",
	"RtCnObvmCA08CEmV1KMZlFuC6c0Gzt5Jsg3XKCM2ynnR6nFx9UNJCg//8H17e/u1khS9afu+4vzu8IIH",
	"fxkHOPaq6PawRnZhBGo5my/G0yUpCmPL6sE0jlIvN2sOdXPitx00uXJ7cPRvNbL3CxJufWTCmsgugN4e",
	"4HjACM67jPBNW2fnFQeAmY/F06UGZu33uhpKCW0E1MJjORtAb5No/QNaOfgXSKwG4m6XSeOyWa+xKsIM",
	"cU/BcfmJjAbKBqnLjywzLt4d1lxrvUgFlnG5OdbnA2jhZfFJmJqZEXxv+93jRv5ycwYjd2Or4m9LUnjc",
	"dWecGfMBdJiCoR2td5b+u7L+GC3sKesf0MKOnF8A5ruEOoDmnyqRMNp4CxdPCGpisBCyc3A2BmPLyqO3",
	"UArI2YCcfU2fov0N44hIqBwlmm5EKoEMCh82RE0dJp28x+M2wKOytQ/oPTDyY3eDLz9gBZ/byK2rmX35",
	"YwRGVyq8o/AKEJkxAJdiX+KNyydXCGzWs28EUudd1nmPFikulxvTwYzfqJJfOfHn72HI67pazSaOF0ed",
	"PHfHPeYXqpKsc15r5J1ZlLOvaXdISczA4A7MnSjzxygQLEnRe+wEQGsZepsmu17eJ44JrI/4ZZcb/8/4",
	"Jrj7QNmP1GrnnCmfyIh+g7yUv9cFYChVnE5p71jMqJ8+laR1FzsmMC7W1QWKzzdh6LAYT9MnMCLwe0tS",
	"BEpTMJstSdEfbbYbQM7HQJvFUpKidq6/B8jZGHq8ho6CJWndz1EQT+CXVR11Q+Om7rROS3tJivb3AHpI",
	"GchVoi/TSLSgveHiMkwTRUXRGiAMsdDv9oma8/BdutfSv/wzhVftYwZxc7aYPEJbO2rmJYYY8V6NS3NW",
	"O8vgoNOnMBIrJo/0dYxbZD2+L3bAFQ4YQWAmaO0tMuMGfiifVI8PKdHoeVLOHyuJGRTIo+dJtHxQksJa",
	"DklztfQqCuQxk/hW5KKgbakP2jUYqcigTJ8xOB6wOCo0Dhzj2hMXxo1G5klTM7SWAXYTf89uon1lepqS",
	"fKtIK8qLIC1YtJ5EOf2iFvLljrYYSKiFOVAdlLDISTzQRx5N8IU3xcCWkkyr6W27SVk4gBsp9eQx/sZa",
	"Bj59LWcDSiRcbpV8oUWWqTOS9sDlpw0D7GfMjt5sYCPno75sXj592rjGatgTxKFfa2XRXpq69wptLsG5",
	"nK47+EXCbdjbw2GBdfoFtzgxgjnWkgPy0m6/ePf80w9lU7r+s82kdapJi4F2vion3xVFL22pu7k7fLll",
	"z1D+aFZsGuOv+u6x46zIc/XRUHcTaNPGxAycDRWnU6D7Rh+AO4+V3C4JBnZOye3CdKIkJezcVUDreWph",
	"tFkhnxaUeAo4fsFFSjPQ6rFmrZr5fTPAEPg9vkFr5N9POkCldLJzgDYvwHfA4jDuDJDb2DarewO0CaUk",
	"ZmjPo6bRgA8uD8XrZuVROkktj1nLl+mQ4CoggZEaC0DRSNV7W0hN2YIfGSFPfHPFAdDaC3gwQ8dD+CEi",
	"KwC0vs0/Zp/QgL1OqMEfOywWc4el1dxhaTd3WDrMHZb/NHe0XTOTaLx+rfxYp8Vi7rS04suarCqs4Poz",
	"vwMc+J0tmkCCCTqv13REKumStK5nBy6+lk9JDUrS37NAsL+HjIoBKAYW0dqCnH+lLM1SnWLZvl9V3j+B",
	"uV2sscUTTUBwK6ckA2r6E1o5pQkwcJixE/6b1rLRkmn8KaYeHVCCqNKxZyNJN21iY8lg/oCSf4ap+KP/",
	"NitwrMiWnTklpZyXiG5xvAbdGLA6n9ZlsrS0tlgw5nkvyzFet6nL1E4uNZu8jHiXWJ+Z8brND1rNjF+8",
	"a6b5+RhrVOWR/Yh/rvldkqIab5/1KHbuS2ZcaPVYLcRBh6W1JIUdNROuSFks2NUR0vpcpi7TH1gR0zuA",
	"E+WqRZU2i+VfNt/TxQnDcbBe4+s06lFhotVj2hFp0WThAGgpB7O71KVTT4497mSzqcPS2oiOCmPmqvHl",
	"ZLOpk3L5+S9Vr3bofTSJdnrv/Jdbk7eaTT6/x8MIE7hWIsql1FbHDp2CMVaZMR+ZR+BTbuFXVKGuMpPB",
	"lYZBRXaSUeLvmprg3iMlH25qwpnCbPQsMOW4/rNtdMT6/bDV5gA4AJIRtpyNAwcGx2iv9adR29AfrYOj",
	"1kEyLP9OFPysw86h1WM6RAJ07kMIIBPxXRh+phbieqVRr/xdq8XyLdn50UasdYN4UobULgKRwbhd2+XA",
	"FfT+GtxI2U1ydqF8VX35BoYOSd7S1KTEt+TcnrKQgS+nYSFUTOYrGwJNTQYAp7MyrB2bNuQRaAO0h3dN",
	"/MsQXjOaNFpWIeKkm1Q0RzjPCLDQJ7+i/RmNdi82RBqSKiboAHB/FaWPqAFSRFRM7wusSLf59isND3+r",
	"/eJvGay2EJutGGXVnPj6z7aSFJbzISgF8FUCrJIU+axR6usxw1hQVd/pu6zhVToZ0DsGWiShWBr8DujL",
	"KQepcxxkdna+QGfnqOWo6aS+xiL4h1KOdpNRYA+Qbzc1laQEzdbUowPgGGa9LCNioQyzjAv8DuD/hrjx",
	"CYedk3OP4HyyJEXlwnM1EwTjbp8I4JMoPQmg5zvq3Gu4FJWzAVh4o4RwSiBnY7KUoCTADDZgOTtvHGr0",
	"RTGJrwLjYUVW8BEvaiQ/uL0HDxbPAlN0FgPacGKkbASV5R0UXpGlF8AC0OoxXN8sBgIwfEAf02pgfMx9",
	"PytMlPuiuPaj3aZzq/EwD7WmscXy+RYyLlcMaQwuKnv5khRWTw7VwpySmFGT0UrNi0sGC8DQ2nvUmC7+",
	"zh0fW0PY5wrjW1/RVxi2Vy52FgYuAm28repLXJ6jqLJ2GF7F+RQxwpIURtGIfmgBA09gbrHa3ssFOy4p",
	"jQMu3EgBR9kJkFIELT6BoR05G0DPk2r6AJ4u4/CL9VsWCv7ObTfncnNjoLh2jK8EEzTNsXMlKWwwgvjD",
	"0PBA3RCCHkZGEdQzqMeh4nKhkijbudqpGm1Ny1IChg9Abw+A76aMLbRqx+mrRkrdHpXRVi5R0G8TK2vn",
	"Ib8O+isHMI9zeOr1f1P0Y1FqUwhiA4ZAN4htZpHx0Z67sQ2g+Xlt4SO5qRbWQTfpeBfXtrDBkV0SugNx",
	"Fpga1pri9BG08VpbpST1ip0zWOnU7eK2U5SXO9DaGmeltl2sbJTjEhatZeyc3VS/2Wk3qYU1tJZRNrZg",
	"elOres9X2etMoX6H5CvZg/GOjhHqqLB/G6NovPj0T+eRLXTZBdf7OYAJ//+ZRNLtIb1h6ReosKclaG9o",
	"bbTr0TCBVOIpClXaYaLTJ+VFsCSF2ywWYKbDmIiSfwbIYGdB3w3BgeUoWJxbhLOHyv4KWTt4ZudqZ6ZK",
	"PKVZEzEEWUqo6b+DynxHPp1tapKzsaam4lwMLmWAl3edBaZoP0+7ox4d2Dmtt1du2VRaW5pLrBR1DTsQ",
	"dNj7NTsQNePkhj+koLO+khRFkQDaiMBCSN0N6sdwGlg1DF0SbRRlKLwCtxNy9rWeqsr+PCGs2vUfvFPy",
	"r6mqcYlDuSAMolcBtLVTnfVogKToJA26huBUC+tK6hHcSKmFJTUZhQfv6FBELcRBm8VC8aYHZM3QpR54",
	"FGF2zsu7cK2z/gLtbxOIqdOnTU0aq/m8fLoMt1eK0ynlMK/kt0pSuLcHmAGNL5VhqzHI+glLXzVzrpk9",
	"Ge3fU8ntr6EPeQONketURo00ozUqW8q0GSpIzu+A6yNDgwCevoTSolZszobgUVRJzIAhL8t13+gD7S2t",
	"QN2bUaPT2K4XMzAjwdAOuMH7RA/DATPoEfwcD8x2ro/z8R7OzWAhK0uz6t6ryiFKYgae7MDQCS4O51P0",
	"JziV+AzMwMM77zXUinbKiJd1/l91Y7wagCNM/ZilTjF6kfi8rLNeOZoQF7bg3iNQ+7hOWx5WZLCuSJtQ",
	"eGBc3/bzTmYcuFgSRD0sJ4Jv3B4vL4jAxd5h/OPifwGzi3f6AP+AFQS3i/UBRgSCnxPdHvaKqdnkF8a1",
	"4U6X2dza9h8tlhZLS2tXu8ViIatoGjV1hYvO/CvrKJV+/OetFhdPejPHhkrs185VLBgQA47grLjS18en",
	"1oaeij+q+C98aM2CgZ2TszF6rs6wtZpZM4r6svz6zzZAB300LBMGz7uoDiDnQ9q8VNfxqf/tAJlnb8m5",
	"PdpfpFzZOUd5DuAA9BTtZ5EGLV748Vhr7us7+ecskL5SPQP6fhGORFJc2c7RDUC63kkWOBL6H2WSCZCP",
	"piza2I1cElgv73OLvDAB1KVTmHtq5/Bl483hlQOUSsLnq0poT338Rp3fVeJ55elLGDuEi5ka0tnK8kAt",
	"9WQkWF6pohArSeGyvWBbAWagm11H9L8iwNn8owh9Su9O5PwruhCsp4EY2uStyf8NAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
